###########
# site.title

title:    'Plagiarism'
subtitle: 'Minecraft Copier'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md

theme: jekyll-theme-cayman